services:
  # Сервис для MongoDB

  mongodb:
    image: mongo # Загружаем последнюю стабильную версию MongoDB
    container_name: mongodb # Уникальное имя контейнера для MongoDB
    volumes:
      - mongodb-data:/data/db # Храним данные MongoDB в volume для постоянства
    networks:
      - mongodb-backend # Внутренняя сеть для взаимодействия с другими сервисами

  # Сервис для MongoDB Express (веб-интерфейс для работы с MongoDB)
  express:
    image: mongo-express # Используем образ MongoDB Express для доступа через UI
    container_name: express # Уникальное имя контейнера для Express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
    ports:
      - "8081:8081" # Открываем порт 8081 для доступа к Express через веб-браузер
    networks:
      - mongodb-backend # Внутренняя сеть для взаимодействия с другими сервисами
      - mongodb-frontend # Публичная сеть для внешнего доступа к MongoDB Express

volumes:
  # Volume для хранения данных MongoDB
  mongodb-data:


networks:
  # Внутренние и публичные сети
  mongodb-backend: # Сеть для связи между сервисами внутри контейнеров
  mongodb-frontend: # Публичная сеть для доступа к MongoDB Express
